version: '3.3'

networks:
  rgp-network:
    external: true

services:
  service:
    container_name: {serviceName}-service
    image: node:14-alpine
    working_dir: /var/www/rgp-service
    volumes:
      - .:/var/www/rgp-service
    environment:
      - NODE_ENV=local
      - SERVICE_PORT={port}
      # TOKEN must be in .env file
      - VERCEL_TOKEN=${VERCEL_TOKEN}
    ports:
      - "{port}:{port}"
    networks:
      rgp-network:
        aliases:
          - {serviceName}.service.localhost

    command: "npm run start-docker"
